export const styles = {
  statsContainer: {
    display: "flex",
    alignItems: "center",
    gap: "20px",
    backgroundColor: "white",
    padding: "20px",
    borderRadius: "8px",
    marginBottom: "20px",
    border: "1px solid #e2e8f0",
  },
  statItem: {
    display: "flex",
    flexDirection: "column",
  },
  statLabel: {
    fontSize: "12px",
    textTransform: "uppercase",
    color: "#64748b",
    fontWeight: "bold",
    marginBottom: "4px",
  },
  statValue: {
    fontSize: "24px",
    fontWeight: "bold",
    color: "#1b1b1b",
    fontFamily: "Oswald, sans-serif",
  },
  statDivider: {
    width: "1px",
    height: "40px",
    backgroundColor: "#e2e8f0",
  },
  toolbar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
    flexWrap: "wrap",
    gap: "10px",
  },
  filterGroup: {
    display: "flex",
    gap: "8px",
    overflowX: "auto",
    paddingBottom: "4px",
  },
  filterBtn: {
    padding: "8px 16px",
    borderRadius: "6px",
    border: "1px solid",
    fontSize: "14px",
    cursor: "pointer",
    whiteSpace: "nowrap",
    transition: "all 0.2s",
  },
  exportBtn: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 16px",
    backgroundColor: "white",
    border: "1px solid #e2e8f0",
    borderRadius: "6px",
    color: "#1b1b1b",
    fontSize: "14px",
    cursor: "pointer",
    fontWeight: "500",
  },
  searchWrapper: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "white",
    border: "1px solid #e2e8f0",
    borderRadius: "6px",
    padding: "8px 12px",
    width: "250px",
  },
  inputReset: {
    border: "none",
    outline: "none",
    width: "100%",
    fontSize: "14px",
  },
  tableContainer: {
    backgroundColor: "white",
    borderRadius: "8px",
    border: "1px solid #e2e8f0",
    overflow: "hidden",
  },
  emptyState: {
    padding: "40px",
    textAlign: "center",
    color: "#64748b",
    fontSize: "16px",
  },
  toast: {
    position: "fixed",
    bottom: "20px",
    right: "20px",
    backgroundColor: "#10b981",
    color: "white",
    padding: "12px 24px",
    borderRadius: "8px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    boxShadow: "0 4px 6px rgba(0,0,0,0.1)",
    zIndex: 1000,
    fontWeight: "500",
  },
};
